---
- name: To gather facts of the web server
  hosts: local
  connection: local
  tasks:
  - name: To gather facts of the web server
    ansible.builtin.debug:
      var: ansible_facts
  - name: To gather facts of the web server
    ansible.builtin.debug:
      var: ansible_facts['all_ipv4_addresses']
