---
- name: Install and start nginx
  hosts: web
  become: true
  tasks:
  - name: Install NGINX
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Enable and Start NGINX Service
    ansible.builtin.service:
      name: nginx
      enabled: true
      state: started
