---
- name: Prints Variable Information
  hosts: web
  vars:
    COURSE: "DEVOPS"
    DAYS: "120 Days"
    TUTOR: "Siva"
  tasks:
  - name: Print Variable Info
    ansible.builtin.debug:
      msg: Course {{ COURSE }} will complete in {{ DAYS }} days by {{ TUTOR }}"
