---
- name: Prints Variable Information
  hosts: web
  vars_files:
  - course.yaml
  tasks:
  - name: Print Variable Info
    ansible.builtin.debug:
      msg: Course {{ COURSE }} will complete in {{ DAYS }} by {{ TUTOR }}
