---
- name: Check the variables priority 
  hosts: local
  connection: local
  # Variables at play level
  vars:
    COURSE: 'Ansible at play level'
  # variables using vars-files
  vars_files:
    - course.yaml  
  # variables using vars_prompt 
  vars_prompt:
    - name: provide the username
      prompt: username
      private: false
  tasks:
      # variables at play level
    - name: Variables at play level
      # vars:
      #   COURSE: 'Ansible at Task level'
      ansible.builtin.debug:
         msg: "MY Course is {{ COURSE }} "





