---
- name: Gathering Facts
  hosts: local
  connection: local
  tasks:
    # - name: Gathering Facts
    #   ansible.builtin.debug:
    #     var: ansible_facts
    -
       ansible.builtin.debug:
         var: ansible_facts.distribution