---
- name: loops print names
  hosts: local
  connection: local
  tasks:
   - name: print names provided
     ansible.builtin.debug:
       msg: "My Name is {{ item }}"
     loop:
       - Mahesh
       - Keerthi
       - Parnika
       - Jeevika