---
- name: filters from ansible 
  hosts: local
  connection: local
  tasks:
    - name: use filters ansible
      ansible.builtin.debug:
        msg: "Hi Mahesh {{ Greetings | default(Good Morning)}}"