---
- name: convert dict to items  
  hosts: local
  connection: local
  vars:
    tags:
      - { "key":"name", "value": "terraform" }
      - { "key": "course" , "value": "devops" }
      - { "key": "component", "value": "cart" }

  tasks:
   - name: Covert dict to item.state
     ansible.builtin.debug:
       msg: "{{ tags | items2dict }}"