---
- name: convert dict to items  
  hosts: local
  connection: local
  tasks:
   - name: get file students.yaml
     include_vars:
      file: students.yaml
      name: students_data
     ansible.builtin.debug:
       msg: "{{ students_data | to_nice_json }}"

       