---
- name: check if user exists or not
  hosts: local
  connection: local
  ignore_errors: true
  tasks:
  - name: check if user roboshop exists or not
    ansible.builtin.command: id roboshop
    register: user_output

  - name: Print user user_output
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: create user
    ansible.builtin.command: useradd roboshop
    when: rc!= 0
