---
- name: Playbook Play-1
  hosts: local
  connection: local
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

- name: Playbook Play-2
  hosts: local
  connection: local
  tasks:
  - name: Install nginx
    ansible.builtin.user:
      name: keeru
      state: present
